title: Philo Conda
description: Documents des leçons de philosophie des classes de Terminale de R. Auda
theme: just-the-docs
baseurl: "/philotg" # the subpath of your site, e.g. /blog
url: https://rollauda.github.io/
repository: rollauda/philotg # for github-metadata
aux_links:
  Notions: https://rollauda.github.io/philotg/docs/Pr%C3%A9sentation/L0-2-tableau.html
  Index : https://rollauda.github.io/philotg/docs/Pr%C3%A9sentation/L0-3-notions.html
  Méthode: https://rollauda.github.io/philotg/docs/methode.html
  CdT: https://rollauda.github.io/philotg/docs/divers/cdt/cdt.html
  HVC TB: https://rollauda.github.io/philotg/docs/divers/PPTB/pptb.html
  Sc-po: https://rollauda.github.io/philotg/docs/divers/spo/spo.html
  Accueil-Auda: https://rollauda.github.io

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# For copy button on code
enable_copy_code_button: true

# Enable or disable heading anchors
heading_anchors: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: lightb

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  nouveau:
    title: Nouveau
    color: green
  note:
    title: Note
    color: purple
  attention:
    title: Warning
    color: red
  gris:
    title: gris
    color: grey-lt 
  gris2:
    title: gris
    color: grey-dk

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.1.0"

  defaults:
  - scope:
      path: "assets/img"
    values:
      image: true